name: flamedemo
description: Flutter bare flame game.
#
#publish_to: 'none'
#
#version: 1.0.0+1
#
#environment:
#  sdk: ">=2.17.6 <3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.2
#  flame: ^1.9.1
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#  flutter_lints: ^2.0.0
#
#flutter:
#
#  uses-material-design: true
#
version: 0.0.0
publish_to: none

environment:
  sdk: ^2.16.0
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.9.1
